"""criar tabela charges

Revision ID: 33f1693378a4
Revises: d24e8b91fa07
Create Date: 2026-09-07 17:06:09.708830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33f1693378a4'
down_revision: Union[str, Sequence[str], None] = 'd24e8b91fa07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('payment_url', sa.String(), nullable=True),
    sa.Column('digitable_line', sa.String(), nullable=True),
    sa.Column('pix_copy_paste', sa.String(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'PAID' AND paid_at IS NOT NULL) OR (status <> 'PAID' AND paid_at IS NULL)", name='check_charge_paid_at_matches_status'),
    sa.CheckConstraint("status IN ('PENDING', 'PAID', 'OVERDUE', 'CANCELLED')", name='check_charge_status_valid'),
    sa.CheckConstraint('(external_id IS NULL AND issued_at IS NULL) OR (external_id IS NOT NULL AND issued_at IS NOT NULL)', name='check_charge_issued_consistency'),
    sa.CheckConstraint('amount > 0', name='check_charge_amount_positive'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name='fk_charges_client_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id', name='uq_charges_external_id')
    )
    # O Postgres não indexa chave estrangeira automaticamente.
    op.create_index('ix_charges_client_id', 'charges', ['client_id'])
    # Atende a consulta da rotina diária de vencimentos.
    op.create_index('ix_charges_status_due_date', 'charges', ['status', 'due_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_charges_status_due_date', table_name='charges')
    op.drop_index('ix_charges_client_id', table_name='charges')
    op.drop_table('charges')
    # ### end Alembic commands ###
