"""criar tabela clientes

Revision ID: ec6f5bd69c7c
Revises: 
Create Date: 2026-07-22 16:21:12.511800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec6f5bd69c7c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('tipo_pessoa', sa.String(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=True),
    sa.Column('cnpj', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(tipo_pessoa = 'FISICA' AND cpf IS NOT NULL AND cnpj IS NULL) OR (tipo_pessoa = 'JURIDICA' AND cnpj IS NOT NULL AND cpf IS NULL)", name='check_documento_por_tipo_pessoa'),
    sa.CheckConstraint("tipo_pessoa IN ('FISICA', 'JURIDICA')", name='check_tipo_pessoa_valido'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clientes')
    # ### end Alembic commands ###
